name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 1 * * *" # Se ejecuta a la 1 AM todos los días
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate 3D Graph
        uses: yoshi389111/github-profile-3d-contrib@v0.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: PIKY-505
          SETTING_JSON: "theme-3d.json"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update 3D contribution graph with custom hacker theme"
          branch: main
          file_pattern: profile-3d-contrib/*
