name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta a medianoche todos los días
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Snake files
        uses: Platane/snk@v3
        with:
          github_user_name: PIKY-505
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=red&color_dots=#000000,#4d0000,#990000,#e60000,#ff0000
            dist/github-contribution-grid-snake-dark.svg?color_snake=red&color_dots=#000000,#4d0000,#990000,#e60000,#ff0000

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake animation with hacker palette"
          branch: main
          file_pattern: dist/*
